version: '3'

networks:
  service_network:
    external: true

services:
  son-gtkapi:
    build: ./son-gtkapi
    image: son-gtkapi:SNAPSHOT
    env_file: ./docker-compose-env
    container_name: son-gtkapi
    networks:
      - service_network
    restart: always
    ports:
      - "32001:80"
    depends_on:
      - son-gtkpkg
      - son-gtksrv
      - son-gtkfnct
      - son-gtkvim
      - son-gtkrec

  son-gtkpkg:
    build: ./son-gtkpkg
    image: son-gtkpkg:SNAPSHOT
    env_file: ./docker-compose-env
    container_name: son-gtkpkg
    networks:
      - service_network
    restart: always

  son-gtkfnct:
    build: ./son-gtkfnct
    image: son-gtkfnct:SNAPSHOT
    env_file: ./docker-compose-env
    container_name: son-gtkfnct
    networks:
      - service_network
    restart: always

  son-gtkrec:
    build: ./son-gtkrec
    image: son-gtkrec:SNAPSHOT
    env_file: ./docker-compose-env
    container_name: son-gtkrec
    networks:
      - service_network
    restart: always

  son-gtksrv:
    build: ./son-gtksrv
    image: son-gtksrv:SNAPSHOT
    env_file: ./docker-compose-env
    container_name: son-gtksrv
    networks:
      - service_network
    restart: always
    depends_on:
      - postgres
      - broker

  son-gtkvim:
    build: ./son-gtkvim
    image: son-gtkvim:SNAPSHOT
    env_file: ./docker-compose-env
    container_name: son-gtkvim
    networks:
      - service_network
    restart: always
    depends_on:
      - postgres
      - broker

  postgres:
    image: ntboes/postgres-uuid
    env_file: ./docker-compose-env
    container_name: postgres
    networks:
      - service_network

  broker:
    image: rabbitmq:3
    env_file: ./docker-compose-env
    container_name: broker
    networks:
      - service_network
